const EQUIPAMENTOS_VAESEN = {
  protecoes: [
    { nome: "Armadura Leve", protecao: 2, agilidade: -1, disponibilidade: 2 },
    { nome: "Armadura Média", protecao: 4, agilidade: -2, disponibilidade: 3 },
    { nome: "Armadura Pesada", protecao: 6, agilidade: -3, disponibilidade: 4 }
  ],

  equipamentosGerais: [
    { nome: "Armadilha de caça", bonus: "+1", disponibilidade: 1, efeito: "Detectar pessoas se esgueirando com VIGILÂNCIA" },
    { nome: "Binóculos", bonus: "+2", disponibilidade: 2, efeito: "Usar VIGILÂNCIA de longe" },
    { nome: "Binóculos de teatro", bonus: "+1", disponibilidade: 1, efeito: "Usar VIGILÂNCIA de longe" },
    { nome: "Bússola", bonus: "+1", disponibilidade: 2, efeito: "Usar APRENDIZADO para encontrar o caminho" },
    { nome: "Equipamento de caça", bonus: "+2", disponibilidade: 2, efeito: "Usar INVESTIGAÇÃO na selva" },
    { nome: "Gazuas", bonus: "+1", disponibilidade: 2, efeito: "Abrir fechaduras com FURTIVIDADE" },
    { nome: "Lamparina a querosene", bonus: "+2", disponibilidade: 1, efeito: "Usar INVESTIGAÇÃO na escuridão e detectar pessoas se esgueirando com VIGILÂNCIA" },
    { nome: "Pé-de-cabra", bonus: "+1", disponibilidade: 2, efeito: "Quebrar trancas com FORÇA" },
    { nome: "Pederneira", bonus: "+1", disponibilidade: 1, efeito: "Usar INVESTIGAÇÃO em locais escuros" },
    { nome: "Ataduras simples", bonus: "+1", disponibilidade: 1, efeito: "Necessário para MEDICINA" },
    { nome: "Bola de cristal", bonus: "+1", disponibilidade: 3, efeito: "Usar OBSERVAÇÃO para procurar pistas" },
    { nome: "Câmera", bonus: "+2", disponibilidade: 3, efeito: "Obter conhecimento sobre um local com APRENDIZADO ou INVESTIGAÇÃO" },
    { nome: "Cão de companhia", bonus: "+1", disponibilidade: 1, efeito: "Usar em COMBATE CORPO A CORPO" },
    { nome: "Cão de guarda", bonus: "+2", disponibilidade: 2, efeito: "Usar em VIGILÂNCIA e COMBATE CORPO A CORPO" },
    { nome: "Cão de caça", bonus: "+3", disponibilidade: 3, efeito: "Usar em VIGILÂNCIA, COMBATE CORPO A CORPO e INVESTIGAÇÃO" },
    { nome: "Cavalo fraco", bonus: "+1", disponibilidade: 2, efeito: "Usar FORÇA" },
    { nome: "Cavalo forte", bonus: "+2", disponibilidade: 3, efeito: "Usar em COMBATE CORPO A CORPO e FORÇA" },
    { nome: "Coleção de livros", bonus: "+1", disponibilidade: 2, efeito: "Encontrar informação com APRENDIZADO" },
    { nome: "Corda", bonus: "+1", disponibilidade: 1, efeito: "Usar FORÇA para escalar" },
    { nome: "Cozinha de campo", bonus: "+2", disponibilidade: 2, efeito: "Cozinhar com INSPIRAÇÃO" },
    { nome: "Disfarce", bonus: "+2", disponibilidade: 2, efeito: "Às vezes necessário para MANIPULAÇÃO" },
    { nome: "Disfarce elegante", bonus: "+2", disponibilidade: 3, efeito: "Às vezes necessário para MANIPULAÇÃO e pode ser usado para se esgueirar com MANIPULAÇÃO" },
    { nome: "Equipamento médico", bonus: "+2", disponibilidade: 2, efeito: "Necessário para MEDICINA" },
    { nome: "Equipamento químico", bonus: "+1", disponibilidade: 2, efeito: "Determinar a causa da morte com INVESTIGAÇÃO" },
    { nome: "Escada de corda", bonus: "+3", disponibilidade: 2, efeito: "Usar FORÇA ou AGILIDADE para escalar" },
    { nome: "Instrumento musical", bonus: "+1", disponibilidade: 2, efeito: "Influenciar ouvintes com INSPIRAÇÃO" },
    { nome: "Instrumento musical obra-prima", bonus: "+2", disponibilidade: 3, efeito: "Influenciar ouvintes com INSPIRAÇÃO" },
    { nome: "Laboratório portátil", bonus: "+1", disponibilidade: 3, efeito: "Produzir veneno com APRENDIZADO" },
    { nome: "Licor", bonus: "+1", disponibilidade: 1, efeito: "INSPIRAR com álcool" },
    { nome: "Livro de mapas", bonus: "+1", disponibilidade: 2, efeito: "Usar INVESTIGAÇÃO e APRENDIZADO para navegar pelo terreno" },
    { nome: "Lupa", bonus: "+1", disponibilidade: 2, efeito: "Encontrar pistas durante a INVESTIGAÇÃO" },
    { nome: "Maquiagem", bonus: "+1", disponibilidade: 1, efeito: "Às vezes necessária para MANIPULAÇÃO" },
    { nome: "Panela", bonus: "+1", disponibilidade: 1, efeito: "Cozinhar com INSPIRAÇÃO" },
    { nome: "Papel e utensílios de escrita", bonus: "+1", disponibilidade: 1, efeito: "Fazer anotações durante a INVESTIGAÇÃO" },
    { nome: "Pergaminhos antigos", bonus: "+2", disponibilidade: 3, efeito: "Encontrar informação com APRENDIZADO" },
    { nome: "Provisões simples", bonus: "+1", disponibilidade: 1, efeito: "—" },
    { nome: "Provisões nutritivas", bonus: "+1", disponibilidade: 2, efeito: "—" },
    { nome: "Régua de cálculo", bonus: "+1", disponibilidade: 2, efeito: "Fazer cálculos com APRENDIZADO" },
    { nome: "Veneno fraco (3 doses)", bonus: "—", disponibilidade: 1, efeito: "Necessário para envenenar alguém (toxicidade 3)" },
    { nome: "Veneno forte (2 doses)", bonus: "—", disponibilidade: 2, efeito: "Necessário para envenenar alguém (toxicidade 6)" },
    { nome: "Veneno extremamente forte (1 dose)", bonus: "—", disponibilidade: 3, efeito: "Necessário para envenenar alguém (toxicidade 9)" },
    { nome: "Vinhos finos", bonus: "+1", disponibilidade: 2, efeito: "INSPIRAR e MANIPULAR com álcool" }
  ],

  armasCorpoACorpo: [
    { nome: "Alabarda", dano: 3, alcance: "0", bonus: "+1", disponibilidade: 4, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Baioneta", dano: 2, alcance: "0", bonus: "+1", disponibilidade: 3, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Cadeira", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Cajado", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Chicote", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Chute ou soco", dano: 1, alcance: "0", bonus: "±0", disponibilidade: "—", pericia: "FORÇA" },
    { nome: "Coronha de rifle", dano: 1, alcance: "0", bonus: "+1", disponibilidade: "—", pericia: "COMBATE CORPO A CORPO" },
    { nome: "Espada ou sabre", dano: 2, alcance: "0", bonus: "+2", disponibilidade: 4, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Faca ou adaga", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Machado", dano: 2, alcance: "0", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Mangual", dano: 2, alcance: "0", bonus: "+2", disponibilidade: 4, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Marreta", dano: 2, alcance: "0", bonus: "±0", disponibilidade: 2, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Pé-de-cabra", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 2, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Rapieira", dano: 1, alcance: "0", bonus: "+2", disponibilidade: 3, pericia: "COMBATE CORPO A CORPO" },
    { nome: "Soqueira", dano: 1, alcance: "0", bonus: "+1", disponibilidade: 2, pericia: "COMBATE CORPO A CORPO" }
  ],

  armasDistancia: [
    { nome: "Arco", dano: 1, alcance: "0–2", bonus: "+1", disponibilidade: 1, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Arco longo", dano: 2, alcance: "1–3", bonus: "+1", disponibilidade: 2, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Besta", dano: 2, alcance: "0–1", bonus: "+1", disponibilidade: 3, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Canhão", dano: 5, alcance: "2–5", bonus: "+1", disponibilidade: 5, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Lança", dano: 1, alcance: "0–1", bonus: "+1", disponibilidade: 1, pericia: "COMBATE CORPO A CORPO / COMBATE À DISTÂNCIA" },
    { nome: "Mosquete", dano: 2, alcance: "1–2", bonus: "+1", disponibilidade: 3, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Pistola ou revólver", dano: 2, alcance: "0–1", bonus: "+2", disponibilidade: 4, pericia: "COMBATE À DISTÂNCIA" },
    { nome: "Rifle", dano: 2, alcance: "1–3", bonus: "+2", disponibilidade: 4, pericia: "COMBATE À DISTÂNCIA" }
  ]
};
